// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBvr0aCeVnfnWJ3s75ibuaK6IrNOTUPIg',
    appId: '1:95344340991:web:bc57e10bf272d6a928c1ca',
    messagingSenderId: '95344340991',
    projectId: 'habitbuilder-94d83',
    authDomain: 'habitbuilder-94d83.firebaseapp.com',
    storageBucket: 'habitbuilder-94d83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF-Rd4BmJeb1zo2cFS5NNPfsRI3l13I7A',
    appId: '1:95344340991:android:7792411abb4ba1be28c1ca',
    messagingSenderId: '95344340991',
    projectId: 'habitbuilder-94d83',
    storageBucket: 'habitbuilder-94d83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz-hX4QB0P-vo2oTl-kj1e49WlRMXoaFM',
    appId: '1:95344340991:ios:4eb429cf380d1abf28c1ca',
    messagingSenderId: '95344340991',
    projectId: 'habitbuilder-94d83',
    storageBucket: 'habitbuilder-94d83.appspot.com',
    iosClientId: '95344340991-b51tstkj16phraek7njtgf5c44crnpms.apps.googleusercontent.com',
    iosBundleId: 'com.infusibleCoders.habitBuilderApp',
  );
}
